// default package
// Generated Jun 12, 2013 9:28:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Esientitydef generated by hbm2java
 */
public class Esientitydef implements java.io.Serializable {

	private EsientitydefId id;
	private Esientity esientity;
	private Date effectivedate;
	private String entityname;
	private BigDecimal mvarating;
	private Boolean ispublic;
	private boolean terminated;
	private String description;
	private String location;
	private String aor1;
	private String aor2;
	private String aor3;
	private String aor4;
	private String aor5;

	public Esientitydef() {
	}

	public Esientitydef(EsientitydefId id, Esientity esientity,
			Date effectivedate, String entityname, boolean terminated) {
		this.id = id;
		this.esientity = esientity;
		this.effectivedate = effectivedate;
		this.entityname = entityname;
		this.terminated = terminated;
	}

	public Esientitydef(EsientitydefId id, Esientity esientity,
			Date effectivedate, String entityname, BigDecimal mvarating,
			Boolean ispublic, boolean terminated, String description,
			String location, String aor1, String aor2, String aor3,
			String aor4, String aor5) {
		this.id = id;
		this.esientity = esientity;
		this.effectivedate = effectivedate;
		this.entityname = entityname;
		this.mvarating = mvarating;
		this.ispublic = ispublic;
		this.terminated = terminated;
		this.description = description;
		this.location = location;
		this.aor1 = aor1;
		this.aor2 = aor2;
		this.aor3 = aor3;
		this.aor4 = aor4;
		this.aor5 = aor5;
	}

	public EsientitydefId getId() {
		return this.id;
	}

	public void setId(EsientitydefId id) {
		this.id = id;
	}

	public Esientity getEsientity() {
		return this.esientity;
	}

	public void setEsientity(Esientity esientity) {
		this.esientity = esientity;
	}

	public Date getEffectivedate() {
		return this.effectivedate;
	}

	public void setEffectivedate(Date effectivedate) {
		this.effectivedate = effectivedate;
	}

	public String getEntityname() {
		return this.entityname;
	}

	public void setEntityname(String entityname) {
		this.entityname = entityname;
	}

	public BigDecimal getMvarating() {
		return this.mvarating;
	}

	public void setMvarating(BigDecimal mvarating) {
		this.mvarating = mvarating;
	}

	public Boolean getIspublic() {
		return this.ispublic;
	}

	public void setIspublic(Boolean ispublic) {
		this.ispublic = ispublic;
	}

	public boolean isTerminated() {
		return this.terminated;
	}

	public void setTerminated(boolean terminated) {
		this.terminated = terminated;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getAor1() {
		return this.aor1;
	}

	public void setAor1(String aor1) {
		this.aor1 = aor1;
	}

	public String getAor2() {
		return this.aor2;
	}

	public void setAor2(String aor2) {
		this.aor2 = aor2;
	}

	public String getAor3() {
		return this.aor3;
	}

	public void setAor3(String aor3) {
		this.aor3 = aor3;
	}

	public String getAor4() {
		return this.aor4;
	}

	public void setAor4(String aor4) {
		this.aor4 = aor4;
	}

	public String getAor5() {
		return this.aor5;
	}

	public void setAor5(String aor5) {
		this.aor5 = aor5;
	}

}
