// default package
// Generated Jun 12, 2013 9:28:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Esientity generated by hbm2java
 */
public class Esientity implements java.io.Serializable {

	private BigDecimal entityid;
	private Esientitycategory esientitycategory;
	private String entitytype;
	private BigDecimal assetid;
	private Set esirelationshipentitiesForToentityid = new HashSet(0);
	private Set esirelationshipentitiesForFromentityid = new HashSet(0);
	private Set esientitydefs = new HashSet(0);

	public Esientity() {
	}

	public Esientity(BigDecimal entityid, Esientitycategory esientitycategory) {
		this.entityid = entityid;
		this.esientitycategory = esientitycategory;
	}

	public Esientity(BigDecimal entityid, Esientitycategory esientitycategory,
			String entitytype, BigDecimal assetid,
			Set esirelationshipentitiesForToentityid,
			Set esirelationshipentitiesForFromentityid, Set esientitydefs) {
		this.entityid = entityid;
		this.esientitycategory = esientitycategory;
		this.entitytype = entitytype;
		this.assetid = assetid;
		this.esirelationshipentitiesForToentityid = esirelationshipentitiesForToentityid;
		this.esirelationshipentitiesForFromentityid = esirelationshipentitiesForFromentityid;
		this.esientitydefs = esientitydefs;
	}

	public BigDecimal getEntityid() {
		return this.entityid;
	}

	public void setEntityid(BigDecimal entityid) {
		this.entityid = entityid;
	}

	public Esientitycategory getEsientitycategory() {
		return this.esientitycategory;
	}

	public void setEsientitycategory(Esientitycategory esientitycategory) {
		this.esientitycategory = esientitycategory;
	}

	public String getEntitytype() {
		return this.entitytype;
	}

	public void setEntitytype(String entitytype) {
		this.entitytype = entitytype;
	}

	public BigDecimal getAssetid() {
		return this.assetid;
	}

	public void setAssetid(BigDecimal assetid) {
		this.assetid = assetid;
	}

	public Set getEsirelationshipentitiesForToentityid() {
		return this.esirelationshipentitiesForToentityid;
	}

	public void setEsirelationshipentitiesForToentityid(
			Set esirelationshipentitiesForToentityid) {
		this.esirelationshipentitiesForToentityid = esirelationshipentitiesForToentityid;
	}

	public Set getEsirelationshipentitiesForFromentityid() {
		return this.esirelationshipentitiesForFromentityid;
	}

	public void setEsirelationshipentitiesForFromentityid(
			Set esirelationshipentitiesForFromentityid) {
		this.esirelationshipentitiesForFromentityid = esirelationshipentitiesForFromentityid;
	}

	public Set getEsientitydefs() {
		return this.esientitydefs;
	}

	public void setEsientitydefs(Set esientitydefs) {
		this.esientitydefs = esientitydefs;
	}

}
