server:
    port: 8080

spring:
    profiles:
        active: prod
    data:
        mongodb:
            host: localhost
            port: 27017
            database: jhipster
    thymeleaf:
        mode: XHTML
        cache: true

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: jhipster

http:
    cache:
        timeToLiveInDays: 31


